### ISSUE TITLE
aar file 404

### ISSUE THREAD

**Issue by fulus06** [servo/book#11]
rt:
https://download.servo.org/nightly/android/servo-latest.aar
404
![image](https://github.com/user-attachments/assets/240c53f2-b459-4857-8eef-eb63089c2806)

**Comment by mukilan** [comment]
Thank you for the report! Android builds are not yet published at download.servo.org. The `Building for Android` document was moved from the older Servo wiki page and needs to be updated. 

The `Building for Android` page has a notice regarding the same:
```
https://book.servo.org/hacking/building-for-android.html#note-the-following-instructions-are-outdated-and-might-not-apply-any-longer-they-are-retained-here-for-reference-until-the-android-build-is-fully-functional-and-the-below-instructions-are-reviewed
```

Currently, servo needs to be built locally to obtain the AAR file.

**Comment by jschwe** [comment]
I believe this issue was resolved in the meantime and the link above now works.
