### ISSUE TITLE
ohos: Add java / openjdk to required dependencies

### ISSUE THREAD

**Issue by jschwe** [servo/book#33]
either add it to mach bootstrap or document that openjdk is required to build the .hap package

**Comment by mrobinson** [comment]
We do not have an Android bootstrap any longer, so I think it's fine to make this part of the build instructions for OpenHarmony as we do for all of the Android buildchain dependencies.

**Comment by mukilan** [comment]
@jschwe Is there a MSV of Java that hvigor requires? I have openjdk 17 installed on my Ubuntu VM that I use for OHOS testing. If there is no documented MSV, I can raise a PR saying OpenJDK 17 was used in testing and so we recommend that.

**Comment by jschwe** [comment]
I didn't see any documentation indicating an MSV.  On my mac I'm using the default version available on homebrew (appears to be 23). For mac we should also mention that installing jdk via homebrew requires manually running a step after installing (see https://formulae.brew.sh/formula/openjdk#default)

> For the system Java wrappers to find this JDK, symlink it with
    sudo ln -sfn $HOMEBREW_PREFIX/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk

On fedora I have openjdk 21 installed (again the default) and that also works fine.
