### ISSUE TITLE
Document how to contribute to "the book"

### ISSUE THREAD

**Issue by jschwe** [servo/book#5]
I think there should be a link to this repository in the book, since users reading it might want to contribute to the servo documentation, and currently there doesn't seem to be a direct link to this repository as the source of the rust book.

**Comment by delan** [comment]
There are two links to the book in the top right, but I’ll add one to the title page too:

![image](https://github.com/servo/book/assets/465303/212cbae4-c556-4f59-a0ff-8624f54ba2bf)

**Comment by delan** [comment]
done in e3e58138f6e3b38dbb5b4e7aa8defb36fa0806b3

**Comment by jschwe** [comment]
Thanks 🙏.
